### ISSUE TITLE
can this client support highlighting or facet?

### ISSUE THREAD

**Issue by lin-yf** [oleewere/go-solr-client#2]
I found that the return result does not contain highlighting or facet. 
sorry for my poor English!

**Comment by oleewere** [comment]
@Lin-YF, hey, sorry for late response. yeah maybe it is too strict and can be extended here: https://github.com/oleewere/go-solr-client/blob/master/solr/types.go#L85
This tool was needed for me for main updates (against kerberized Solr), although that can be used for queries as well.

If there is still a need for that I can implement that soon. (there are other go based Solr libs with ZK or facet support, so maybe there are already a better option for you)

**Comment by lin-yf** [comment]
@oleewere ,thank you very much. I have solved it by extending `types.go`  .
```
type SolrResponseData struct {
    ResponseHeader SolrResponseHeader     `json:"responseHeader"`
    Response       SolrResponse           `json:"response"`
    Highlighting   map[string]interface{} `json:"highlighting"`
}
```

Additionally,I found a problem on `README.md`:
```
// Create a query - example
// error
solrQuery := solr.SolrQuery{}

// right
solrQuery := solr.CreateSolrQuery()
```

**Comment by oleewere** [comment]
@Lin-YF , thanks, feel free to open a PR against the master branch with the changes. if you validate that is working and does that you expect, i can create a patch or minor release after the change is merged

**Comment by oleewere** [comment]
@Lin-YF , i applied your suggested changes and created a new release: https://github.com/oleewere/go-solr-client/releases/tag/v0.3.0 , thanks for pointing these, i will close that issue
